"""Functional tests - the API-compatibility evidence.

THIS IS THE MOST IMPORTANT FILE IN THE REPOSITORY.

The Lightwell claim is that a backported fix lands in the exact version you
already run, with the API unchanged and no code migration. The only honest proof
of that claim is an unchanged test suite passing before and after. Not a
scanner, not a version string on a slide - this.

So: do not edit this file between Act 2 and Act 4. If you need to change it to
make Act 4 pass, the remediation broke something and that is a finding worth
more than the demo.

Tests requiring a database are skipped automatically when one is not reachable,
so the suite is still useful on a laptop.
"""
import pytest
from fastapi.testclient import TestClient

from app import db
from app.main import app

client = TestClient(app)

needs_db = pytest.mark.skipif(
    not db.health()["available"],
    reason="No database reachable; set IM_TRAIN_DB_URL to run these",
)


# --------------------------------------------------------------------------- #
# No database required
# --------------------------------------------------------------------------- #

def test_healthz():
    res = client.get("/api/healthz")
    assert res.status_code == 200
    assert res.json()["status"] == "ok"


def test_status_shape():
    """The Status page contract. The demo is filmed around these keys."""
    res = client.get("/api/status")
    assert res.status_code == 200
    body = res.json()

    for key in ("tier", "hostname", "os_version", "arch", "image", "digest",
                "rollback_available", "dependencies", "lightwell", "database",
                "probe"):
        assert key in body, f"missing key: {key}"

    assert "jinja2" in body["dependencies"]
    assert body["lightwell"]["package"] == "jinja2"
    assert isinstance(body["lightwell"]["remediated"], bool)


def test_index_serves_ui():
    res = client.get("/")
    assert res.status_code == 200
    assert "Image Mode Train Service" in res.text


def test_receipt_renders_default_template():
    """Rendering must keep working after remediation - that is the point."""
    from app import receipts

    booking = {
        "reference": "IMT-4100",
        "passenger_name": "D. Chugtai",
        "service_code": "EC 220",
        "origin_name": "Ostrava Hlavni",
        "destination_name": "Praha Hlavni",
        "travel_date": "2026-10-01",
        "depart_time": "06:12:00",
        "price_eur": 28.5,
    }
    out = receipts.render_receipt(None, booking)
    assert "IMT-4100" in out
    assert "Ostrava Hlavni" in out
    assert "28.50" in out


def test_receipt_rejects_unknown_variable():
    """StrictUndefined must still raise, so operator typos fail loudly."""
    from app import receipts

    with pytest.raises(Exception):
        receipts.render_receipt("{{ booking.no_such_field }}", {"reference": "X"})


def test_probe_is_reported():
    res = client.get("/api/probe")
    assert res.status_code == 200
    assert "unsafe_key_emitted" in res.json()


# --------------------------------------------------------------------------- #
# Database required
# --------------------------------------------------------------------------- #

@needs_db
def test_stations_listed():
    res = client.get("/api/stations")
    assert res.status_code == 200
    codes = {s["code"] for s in res.json()}
    assert {"OSR", "PRG", "VIE"} <= codes


@needs_db
def test_search_returns_services():
    res = client.post("/api/search", json={
        "origin": "OSR", "destination": "PRG", "travel_date": "2026-10-01",
    })
    assert res.status_code == 200
    rows = res.json()
    assert len(rows) >= 1
    assert all(r["origin_name"] == "Ostrava Hlavni" for r in rows)


@needs_db
def test_search_rejects_same_station():
    res = client.post("/api/search", json={
        "origin": "OSR", "destination": "OSR", "travel_date": "2026-10-01",
    })
    assert res.status_code == 400


@needs_db
def test_book_then_retrieve():
    services = client.post("/api/search", json={
        "origin": "OSR", "destination": "PRG", "travel_date": "2026-10-01",
    }).json()

    created = client.post("/api/bookings", json={
        "service_id": services[0]["id"],
        "travel_date": "2026-10-01",
        "passenger_name": "Integration Test",
    })
    assert created.status_code == 200
    reference = created.json()["reference"]
    assert reference.startswith("IMT-")

    listed = client.get("/api/bookings").json()
    assert reference in {b["reference"] for b in listed}


@needs_db
def test_receipt_preview_for_real_booking():
    bookings = client.get("/api/bookings").json()
    assert bookings, "seed data missing; run sql/seed.sql"

    res = client.post("/api/receipt/preview", json={"booking_id": bookings[0]["id"]})
    assert res.status_code == 200
    assert bookings[0]["reference"] in res.json()["receipt"]


@needs_db
def test_receipt_preview_unknown_booking():
    res = client.post("/api/receipt/preview", json={"booking_id": 999999})
    assert res.status_code == 404


@needs_db
def test_seed_booking_survives():
    """Referenced in Act 4: /var persisted across the image upgrade.

    The seeded booking must still be present after bootc upgrade and reboot.
    """
    listed = client.get("/api/bookings").json()
    assert any(b["passenger_name"] == "D. Chugtai" for b in listed), (
        "Seeded booking absent. Either seed.sql was not applied, or PGDATA is "
        "not under /var and did not survive the upgrade."
    )
